const JWT_SECRET=process.env.JWT_SECRET;
const EMAILJS_PUBLIC_KEY=process.env.EMAILJS_PUBLIC_KEY;
const EMAILJS_SERVICE_ID=process.env.EMAILJS_SERVICE_ID;
const EMAILJS_TEMPLATE_ID=process.env.EMAILJS_TEMPLATE_ID;
module.exports={
    JWT_SECRET,
    EMAILJS_PUBLIC_KEY,
    EMAILJS_SERVICE_ID,
    EMAILJS_TEMPLATE_ID
}